### ISSUE TITLE
New / updated version from ported storage-plugin.

### ISSUE THREAD

**Issue by masscube** [erenertugrul/construct-plugins#13]
I have change/update the actions DeleteField, DeleteList and DeleteTable. Currently, you can't delete something in the dictionary. When you delete something, it look like this:

**before (json):**
{"test","ok","next":"yo"}

**after delete "test" (json):**
{"test":null,"next":"yo"}

But after my patch, the delete works:

{"next":"yo"}

I have change the code from this..

>       DeleteField(table, list, field)
>         {
>             if (isset(this.storage[table]) && isset(this.storage[table][list]) && isset(this.storage[table][list][field]))
>             {
>                 this.storage[table][list][field] = null;
>                 this.tableAttr[table][list]['fieldCount']--;
>             }
>         }

... to this:

>        DeleteField(table, list, field)
>         {
>             if (isset(this.storage[table]) && isset(this.storage[table][list]) && isset(this.storage[table][list][field]))
>             {
>                 this.storage[table][list][field] = null;
>                 delete this.storage[table][list][field]; // New
>                 this.tableAttr[table][list]['fieldCount']--;
>             }
>         }

**Here my download:**
https://drive.google.com/open?id=1cvrvEkPb_dXJn2OLsoJgYNmW0c5VYIKe

**Comment by erenertugrul** [comment]
thanks for fixing it.
