### ISSUE TITLE
Pin+ behavior for C3 - PinnedUID expression not working

### ISSUE THREAD

**Issue by dop2000** [erenertugrul/construct-plugins#18]
Hi Eren, 
Not sure if it's better to talk to you here or on Construct forum. 
Found a bug in Pin+ plugin, PinnedUID expression doesn't work. I fixed it by changing this in expressions.js:
return(this.pinObject ? this.pinObject.**GetUID()** : -1);

**Comment by erenertugrul** [comment]
thanks for fixing it.
