### ISSUE TITLE
New firebase plugin

### ISSUE THREAD

**Issue by rexrainbow** [erenertugrul/construct-plugins#20]
Sorry for posting message here.

Hi, I am the author of rex plugins, as you know I don't make any construct2/3 plugin anymore.
Now I am studying phaser3 game engine, and rewrite my firebase plugins in pure javascript code, which can be used in any (js) game engine.
Are you interested in wrapping my new firebase plugin to new C3 plugins? It could be paid plugins owned by you.

**Comment by erenertugrul** [comment]
Hi, that would be great. 
I don't get paid to convert plugin or transfer them to c3. when I have time I do it.
if you finish your firebase plugin and share it on github, I can get it from there.
thanks.
