### ISSUE TITLE
Anchor_mod doesn't work with Window bottom/right settings

### ISSUE THREAD

**Issue by dop2000** [erenertugrul/construct-plugins#21]
Hi Eren,
I noticed that anchor_mod behavior doesn't work correctly when you set "Window bottom" or "Window right". See this demo, try resizing the window and restarting the preview several times, every time the position of "Anchor mod" text will be different..
https://www.dropbox.com/s/qmhn9bhmrdhqm3x/anchor_test.c3p?dl=0

If you switch to runtime 2, it works correctly..

Could you fix it please?

**Comment by dop2000** [comment]
Actually, if you don't have time to fix it, no problem.
I don't remember why I used AnchorMod behavior in my project. I think the native Anchor behavior had performance issues, but now when I'm testing - I don't see any difference in performance. So I will probably replace it with the native Anchor.

**Comment by erenertugrul** [comment]
Hi, thank you for the bug report. I will investigate the problem.
