### ISSUE TITLE
Litetween not working anymore in C3 r234.2 - Trim() is not defined

### ISSUE THREAD

**Issue by arcadesindo** [erenertugrul/construct-plugins#26]
Howdy @erenertugrul ! We're so thankful because you've ported the Litetween behavior and supports on C3runtime very well, but we all got this error to happen on C3 release r234.2, could you please give a time for a check on these addons? thank you very much!
![image](https://user-images.githubusercontent.com/28801633/107115938-9cd30d80-68a2-11eb-84bb-33d1577a4c76.png)

![image](https://user-images.githubusercontent.com/28801633/107116010-1d920980-68a3-11eb-8e0d-97b877f1bbe3.png)

**Comment by arcadesindo** [comment]
Current solution : On project settings > Go to Advanced > Change the Scripts Type to Classic
![image](https://user-images.githubusercontent.com/28801633/107117636-4cfa4380-68ae-11eb-9532-c943369a57fe.png)

**Comment by erenertugrul** [comment]
Hi, yes many plugins no longer work in new version
You can temporarily use it in "classic" mode
I will update the plugins

**Comment by arcadesindo** [comment]
Thank you so much!
