### ISSUE TITLE
MoveTo c3runtime

### ISSUE THREAD

**Issue by 1Kenny1** [erenertugrul/construct-plugins#6]
> this.movingAngleStartData["a"] = clamp_angle_degrees(C3.angleTo(this.wi.GetX(), this.wi.GetY(), _x, _y));

> this.movingAngleData["a"] = clamp_angle_degrees(Math.atan2(dy, dx));

Here instead of radians should be degrees
> this.movingAngleStartData["a"] = clamp_angle_degrees(**C3.toDegrees**(C3.angleTo(this.wi.GetX(), this.wi.GetY(), _x, _y)));

> this.movingAngleData["a"] = clamp_angle_degrees(**C3.toDegrees**(Math.atan2(dy, dx)));

**Comment by erenertugrul** [comment]
thank you. i fixed.
