### ISSUE TITLE
easystar C3 plugin 'diagonal disabled bug'

### ISSUE THREAD

**Issue by MikalDev** [erenertugrul/construct-plugins#8]
There's a bug in the original easystar-0.4.1-custom.js

> It's a bug inside the EasyStarJS library. The fix is quite simple and is already present in the up-to-date version. However, my plugin use the v0.4.1 version of the library... Until I find the time to update the plugin files, and if you're not afraid to delve into the javascript, you can edit the "easystar-0.4.1-custom.js" file, and correct all 8 calls to isTileWalkable(). You need to add "searchNode" as the 5th parameter.

Fix: change all occurrences of `isTileWalkable(collisionGrid, acceptableTiles, searchNode.x, searchNode.y - 1)` with `isTileWalkable(collisionGrid, acceptableTiles, searchNode.x, searchNode.y - 1, searchNode)`

**Comment by erenertugrul** [comment]
thanks.
